// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --storage
//
// To manage storage buckets:
//   - Edit src/defs/storage_schema.ts
//   - Apply: edgespark storage apply
//
// Example:
//   export const uploads: BucketDef = {
//     bucket_name: "uploads",
//     description: "User uploaded files",
//   };
//
// Usage in code:
//   import { buckets } from "@generated";
//   await storage.from(buckets.uploads).put("file.jpg", buffer);
// ----------------------------------------------------------------

import type { BucketDef } from "@sdk/server-types";

// No buckets configured for this environment
